# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-16 02:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jack', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='phone_njmber',
            new_name='phone_number',
        ),
    ]
